# This is a basic workflow to help you get started with Actions

name: pages_to_s3

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  
jobs:
  deploy:
    #runner type
    runs-on: ubuntu-latest
    
    #steps
    steps:
    #uses
    - uses: actions/checkout@master
    # - uses: jakejarvis/s3-sync-action@master
    #  with:
    #    args: --acl public-read --follow-symlinks --delete
    #runs
    - name: set envs
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'pages'
        DEST_DIR: 'pages'  
    - name: echo envs
      run: |
        echo $AWS_S3_BUCKET,
        echo $AWS_S3_BUCKET
